server:
  port: 8098
  ssl:
    key-store-password: Bapa123@@@
    key-store: /home/biggview/certificate/biggview.p12
    key-store-type: PKCS12

security:
  require-ssl: true


eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: bgemailservice   #current service name to be used by the eureka server
  mail:
    host: smtp.gmail.com
    port: 587
    username: heebookingmgt@gmail.com
    password: April2020!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true


management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.



